### ISSUE TITLE
Hide Days in DurationBox mode

### ISSUE THREAD

**Issue by sosherof** [jtsage/datebox-builds#2]
Is there an option to hide the days in duration box mode?  I just need hours, minutes and seconds.  I've tried setting the duration format, which works great for the input box results, but can't seem to find an obvious way to hide the days.

I was thinking the dbBoxd class div could be hidden on open, which works but the Days box is briefly visible so it's not ideal.  Would be better if the Days box could just not be built based on an option like "hideDurationDays".

**Comment by jtsage** [comment]
Yep, it's in there.

https://datebox.jtsage.dev/api/#durationOrder
```
overrideDurationOrder: [ 'h', 'i', 's']
```
